/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Daniel Zhabotinsky (https://sketchfab.com/DanielZhabotinsky)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/british-compact-car-low-poly-model-f1e9c43c61bb492a9b15d84f9a16c0f7
title: British compact car - Low poly model
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/TrafficCarNew/scene.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[56.68, 12.43, 0.08]}
            rotation={[0, -Math.PI / 2, 0]}
          >
            <group position={[14.55, 0.34, -2.61]}>
              <mesh
                geometry={nodes.bumper_rear_ASTNMINI_CHROME_0.geometry}
                material={nodes.bumper_rear_ASTNMINI_CHROME_0.material}
              />
            </group>
          </group>
          <group position={[-43.58, 34.17, 0.06]} rotation={[0, 0, 0]}>
            <group position={[2.41, -24.29, 25.79]}>
              <mesh
                geometry={nodes.sidemirrors_ASTNMINI_CHROME_0.geometry}
                material={nodes.sidemirrors_ASTNMINI_CHROME_0.material}
              />
            </group>
          </group>
          <group
            position={[-41.37, 9.94, 24.43]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.31, 0.31, 0.28]}
            >
              <group position={[0.03, 0.15, 12.54]}>
                <mesh
                  geometry={nodes.tier_ASTNMINI_tier_1t_0.geometry}
                  material={nodes.tier_ASTNMINI_tier_1t_0.material}
                />
              </group>
            </group>
            <group
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.31, 0.31, 0.28]}
            >
              <group position={[0.03, 0.15, 12.54]}>
                <mesh
                  geometry={nodes.rim_ASTNMINI_RIMCOLOUR_0.geometry}
                  material={nodes.rim_ASTNMINI_RIMCOLOUR_0.material}
                />
              </group>
            </group>
            <group
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.31, 0.31, 0.28]}
            >
              <group position={[0.03, 0.15, 12.54]}>
                <mesh
                  geometry={nodes.rim_chrome_ASTNMINI_CHROME_0.geometry}
                  material={nodes.rim_chrome_ASTNMINI_CHROME_0.material}
                />
              </group>
            </group>
          </group>
          <group
            position={[-57.31, 10.86, 0.08]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group
              position={[0.06, 0, 1.58]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            >
              <group position={[14.55, 0.34, 2.61]}>
                <mesh
                  geometry={nodes.bumper_front_ASTNMINI_CHROME_0.geometry}
                  material={nodes.bumper_front_ASTNMINI_CHROME_0.material}
                />
              </group>
            </group>
            <group
              position={[0.06, 0, 1.58]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            >
              <group position={[14.55, 0.34, 2.61]}>
                <mesh
                  geometry={nodes.numberplate_front_ASTNMINI_PLASTIC_0.geometry}
                  material={nodes.numberplate_front_ASTNMINI_PLASTIC_0.material}
                />
              </group>
            </group>
          </group>
          <group
            position={[56.26, 20.57, 0.06]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
              <group position={[-97.43, -10.69, 25.79]}>
                <mesh
                  geometry={nodes.backlights_trim_ASTNMINI_CHROME_0.geometry}
                  material={nodes.backlights_trim_ASTNMINI_CHROME_0.material}
                />
              </group>
            </group>
            <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
              <group position={[-97.43, -10.69, 25.79]}>
                <mesh
                  geometry={
                    nodes.backlights_glass_ASTNMINI_headlights_ucb_0.geometry
                  }
                  material={
                    nodes.backlights_glass_ASTNMINI_headlights_ucb_0.material
                  }
                />
              </group>
            </group>
          </group>
          <group
            position={[-55.95, 18.31, 0.06]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
              <group position={[14.78, -8.44, 25.79]}>
                <mesh
                  geometry={nodes.grill_void_ASTNMINI_VOID_0.geometry}
                  material={nodes.grill_void_ASTNMINI_VOID_0.material}
                />
              </group>
            </group>
            <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
              <group position={[14.78, -8.44, 25.79]}>
                <mesh
                  geometry={nodes.grill_ASTNMINI_CHROME_0.geometry}
                  material={nodes.grill_ASTNMINI_CHROME_0.material}
                />
              </group>
            </group>
          </group>
          <group position={[-0.88, 13.4, 0.06]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, 1]} rotation={[Math.PI / 2, 0, 0]}>
              <group position={[-40.29, -4.53, 25.79]}>
                <mesh
                  geometry={nodes.bottom_ASTNMINI_VOID_0.geometry}
                  material={nodes.bottom_ASTNMINI_VOID_0.material}
                />
              </group>
            </group>
            <group
              position={[-40.55, 0.1, -3.46]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group position={[0.18, -0.11, 27.92]}>
                <mesh
                  geometry={nodes.suspension_front_ASTNMINI_VOID_0.geometry}
                  material={nodes.suspension_front_ASTNMINI_VOID_0.material}
                />
              </group>
            </group>
            <group
              position={[40.72, 0.1, -3.46]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group position={[0.18, -0.11, 27.92]}>
                <mesh
                  geometry={nodes.suspension_rear_ASTNMINI_VOID_0.geometry}
                  material={nodes.suspension_rear_ASTNMINI_VOID_0.material}
                />
              </group>
            </group>
          </group>
          <group position={[0.62, 30.16, 0.06]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[58.1, -0.05, -10.2]} rotation={[0, 1.4, 1.57]}>
              <mesh
                geometry={nodes.rear_numperplate_ASTNMINI_PLASTIC_0.geometry}
                material={nodes.rear_numperplate_ASTNMINI_PLASTIC_0.material}
              />
            </group>
            <group position={[10.94, 0, 8.65]} rotation={[Math.PI / 2, 0, 0]}>
              <group position={[-52.73, -28.93, 25.79]}>
                <mesh
                  geometry={nodes.interior_ASTNMINI_VOID_0.geometry}
                  material={nodes.interior_ASTNMINI_VOID_0.material}
                />
              </group>
            </group>
            <group position={[10.94, 0, 10.12]} rotation={[Math.PI / 2, 0, 0]}>
              <group position={[-52.73, -30.4, 25.79]}>
                <mesh
                  geometry={nodes.glass_ASTNMINI_GLASS_0.geometry}
                  material={nodes.glass_ASTNMINI_GLASS_0.material}
                />
              </group>
            </group>
            <group position={[10.9, 0, 20.07]} rotation={[Math.PI / 2, 0, 0]}>
              <group position={[-52.69, -40.36, 25.79]}>
                <mesh
                  geometry={nodes.roof_ASTNMINI_ROOFCOLOUR_0.geometry}
                  material={materials.ASTNMINI_ROOFCOLOUR}
                />
              </group>
            </group>
            <group position={[0.13, 0, -2.03]} rotation={[Math.PI / 2, 0, 0]}>
              <group position={[-41.92, -18.26, 25.79]}>
                <mesh
                  geometry={nodes.bodyshell_ASTNMINI_BODY_0.geometry}
                  material={materials.ASTNMINI_BODY}
                />
              </group>
            </group>
            <group position={[0.13, 0, -2.03]} rotation={[Math.PI / 2, 0, 0]}>
              <group position={[-41.92, -18.26, 25.79]}>
                <mesh
                  geometry={
                    nodes.bodyshell_chrometrim_ASTNMINI_CHROME_0.geometry
                  }
                  material={
                    nodes.bodyshell_chrometrim_ASTNMINI_CHROME_0.material
                  }
                />
              </group>
            </group>
            <group position={[-57.3, 0, -13.91]}>
              <group
                position={[57.43, 0, 11.88]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <group position={[-41.92, -18.26, 25.79]}>
                  <mesh
                    geometry={nodes.turnsignals_trim_ASTNMINI_CHROME_0.geometry}
                    material={nodes.turnsignals_trim_ASTNMINI_CHROME_0.material}
                  />
                </group>
              </group>
              <group
                position={[57.43, 0, 11.88]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <group position={[-41.92, -18.26, 25.79]}>
                  <mesh
                    geometry={
                      nodes.turnsighal_glass_ASTNMINI_headlights_ucb_0.geometry
                    }
                    material={
                      nodes.turnsighal_glass_ASTNMINI_headlights_ucb_0.material
                    }
                  />
                </group>
              </group>
            </group>
            <group position={[-57.85, -19.34, -5.58]}>
              <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <group position={[16.56, -14.71, 6.45]}>
                  <mesh
                    geometry={nodes.headlights_glass_ASTNMINI_GLASS_0.geometry}
                    material={nodes.headlights_glass_ASTNMINI_GLASS_0.material}
                  />
                </group>
              </group>
              <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <group position={[16.56, -14.71, 6.45]}>
                  <mesh
                    geometry={
                      nodes.headlights_reflector_ASTNMINI_headlights_ucb_0
                        .geometry
                    }
                    material={
                      nodes.headlights_reflector_ASTNMINI_headlights_ucb_0
                        .material
                    }
                  />
                </group>
              </group>
              <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <group position={[16.56, -14.71, 6.45]}>
                  <mesh
                    geometry={nodes.headlights_ASTNMINI_CHROME_0.geometry}
                    material={nodes.headlights_ASTNMINI_CHROME_0.material}
                  />
                </group>
              </group>
            </group>
          </group>
          <group
            position={[39.67, 9.94, 24.43]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.31, 0.31, 0.28]}
            >
              <group position={[0.03, 0.15, 12.54]}>
                <mesh
                  geometry={nodes.tier001_ASTNMINI_tier_1t_0.geometry}
                  material={nodes.tier001_ASTNMINI_tier_1t_0.material}
                />
              </group>
            </group>
            <group
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.31, 0.31, 0.28]}
            >
              <group position={[0.03, 0.15, 12.54]}>
                <mesh
                  geometry={nodes.rim001_ASTNMINI_RIMCOLOUR_0.geometry}
                  material={nodes.rim001_ASTNMINI_RIMCOLOUR_0.material}
                />
              </group>
            </group>
            <group
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.31, 0.31, 0.28]}
            >
              <group position={[0.03, 0.15, 12.54]}>
                <mesh
                  geometry={nodes.rim_chrome001_ASTNMINI_CHROME_0.geometry}
                  material={nodes.rim_chrome001_ASTNMINI_CHROME_0.material}
                />
              </group>
            </group>
          </group>
          <group
            position={[39.67, 9.94, -24.29]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.31, 0.31, 0.28]}
            >
              <group position={[0.03, 0.15, 12.54]}>
                <mesh
                  geometry={nodes.rim002_ASTNMINI_RIMCOLOUR_0.geometry}
                  material={nodes.rim002_ASTNMINI_RIMCOLOUR_0.material}
                />
              </group>
            </group>
            <group
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.31, 0.31, 0.28]}
            >
              <group position={[0.03, 0.15, 12.54]}>
                <mesh
                  geometry={nodes.tier002_ASTNMINI_tier_1t_0.geometry}
                  material={nodes.tier002_ASTNMINI_tier_1t_0.material}
                />
              </group>
            </group>
            <group
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.31, 0.31, 0.28]}
            >
              <group position={[0.03, 0.15, 12.54]}>
                <mesh
                  geometry={nodes.rim_chrome002_ASTNMINI_CHROME_0.geometry}
                  material={nodes.rim_chrome002_ASTNMINI_CHROME_0.material}
                />
              </group>
            </group>
          </group>
          <group
            position={[-41.37, 9.94, -24.29]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.31, 0.31, 0.28]}
            >
              <group position={[0.03, 0.15, 12.54]}>
                <mesh
                  geometry={nodes.tier003_ASTNMINI_tier_1t_0.geometry}
                  material={nodes.tier003_ASTNMINI_tier_1t_0.material}
                />
              </group>
            </group>
            <group
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.31, 0.31, 0.28]}
            >
              <group position={[0.03, 0.15, 12.54]}>
                <mesh
                  geometry={nodes.rim003_ASTNMINI_RIMCOLOUR_0.geometry}
                  material={nodes.rim003_ASTNMINI_RIMCOLOUR_0.material}
                />
              </group>
            </group>
            <group
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.31, 0.31, 0.28]}
            >
              <group position={[0.03, 0.15, 12.54]}>
                <mesh
                  geometry={nodes.rim_chrome003_ASTNMINI_CHROME_0.geometry}
                  material={nodes.rim_chrome003_ASTNMINI_CHROME_0.material}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/scene.gltf');
