/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ahasanul Haque (https://sketchfab.com/piprastudio)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/low-poly-car-93971323324243468f24d7da9d18f617
title: Low Poly Car
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
//import { useSpring, a } from 'react-spring/three';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('models/TrafficCar/scene.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-158.9, 67, -212.94]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1, 1, 1]}
          >
            <mesh
              geometry={nodes.WRR_Material027_0.geometry}
              material={nodes.WRR_Material027_0.material}
            />
            <mesh
              geometry={nodes.WRR_Material031_0.geometry}
              material={nodes.WRR_Material031_0.material}
            />
          </group>
          <group
            position={[158.9, 67, -212.94]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.WRL_Material027_0.geometry}
              material={nodes.WRL_Material027_0.material}
            />
            <mesh
              geometry={nodes.WRL_Material031_0.geometry}
              material={nodes.WRL_Material031_0.material}
            />
          </group>
          <group
            position={[158.1, 65.03, 294.55]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.WFL_Material027_0.geometry}
              material={nodes.WFL_Material027_0.material}
            />
            <mesh
              geometry={nodes.WFL_Material031_0.geometry}
              material={nodes.WFL_Material031_0.material}
            />
          </group>
          <group
            position={[0, 160.72, -377.63]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.TailLight_Material030_0.geometry}
              material={materials['Material.030']}
            />
          </group>
          <group
            position={[-158.1, 65.03, 294.55]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.WFR_Material027_0.geometry}
              material={nodes.WFR_Material027_0.material}
            />
            <mesh
              geometry={nodes.WFR_Material031_0.geometry}
              material={nodes.WFR_Material031_0.material}
            />
          </group>
          <group
            position={[0, 138.33, 1.54]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          >
            <mesh
              geometry={nodes.CarBody_Material028_0.geometry}
              material={materials['Material.028']}
            />
            <mesh
              geometry={nodes.CarBody_Carcamero_ma_0.geometry}
              material={materials.Carcamero_ma}
            />
            <mesh
              geometry={nodes.CarBody_Material032_0.geometry}
              material={materials['Material.032']}
            />
            <mesh
              geometry={nodes.CarBody_Material029_0.geometry}
              material={materials['Material.029']}
            />
            <mesh
              geometry={nodes.CarBody_Material026_0.geometry}
              material={materials['Material.026']}
            />
            <mesh
              geometry={nodes.CarBody_Material025_0.geometry}
              material={materials['Material.025']}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/scene.gltf');
