/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: whoiskeo (https://sketchfab.com/whoiskeo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/point-marker-d39c906029df4837a9a0538cbbacd234
title: Point Marker
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/MapPointer/scene.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.LollipopheadusOBJexport_loli_0.geometry}
            material={materials.loli}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/scene.gltf');
